package ai.ecma.appintegrationtest.entity.enums;


public enum Permission {

    ADD_USER,EDIT_USER,DELETE_USER,VIEW_USERS,
    ADD_PERMISSION,EDIT_PERMISSION,DELETE_PERMISSION,VIEW_PERMISSION,
    ADD_ROLE,EDIT_ROLE,DELETE_ROLE,VIEW_ROLE,
    ADD_COURSE,EDIT_COURSE,DELETE_COURSE,
    ADD_MODULE,EDIT_MODULE,DELETE_MODULE,
    ADD_LESSON,EDIT_LESSON,DELETE_LESSON,

}
